## Task Day-13 (21-06-21)

#### Create arrays with all the data types available in numpy


In [1]:
import numpy as np

In [2]:
#boolean
x = np.array([False, False, False, True], dtype = 'bool_')
print(x)
print(x.dtype)

[False False False  True]
bool


In [3]:
#integer
x = np.array([4, 2, 0], dtype = 'int_')
print(x)
print(x.dtype)

[4 2 0]
int32


In [4]:
#Float
x = np.array([6.9, 4.2, 2.2, 8.01, 5.6], dtype = 'float_')
print(x)
print(x.dtype)

[6.9  4.2  2.2  8.01 5.6 ]
float64


In [5]:
#string
x = np.array(['a', 'k', 'y'], dtype = 'S')
print(x)
print(x.dtype)

[b'a' b'k' b'y']
|S1


In [6]:
#complex
x = np.array([3+1j, 1-2j, 2+2.2j], dtype = 'complex_')
print(x)
print(x.dtype)


[3.+1.j  1.-2.j  2.+2.2j]
complex128


In [7]:
#unicode
x = np.array([9, 8, 7, 6], dtype = 'U')
print(x)
print(x.dtype)


['9' '8' '7' '6']
<U1


In [8]:
#unsloved integer
x = np.array([9, 8, 7, 6], dtype = 'uint8')
print(x)
print(x.dtype)


[9 8 7 6]
uint8


In [9]:
#object
x = np.array([[9, 8], [7, 1], [6.9, 4.2], ['dude', 'bruh']], dtype = 'O')
print(x)
print(x.dtype)


[[9 8]
 [7 1]
 [6.9 4.2]
 ['dude' 'bruh']]
object
